name: npm publish

on:
  push:
    tags:
      - 'v*'              # z.B. v1.0.0
  workflow_dispatch:       # manuell auslösbar

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Version gegen Tag prüfen (optional, aber hilfreich)
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "package.json version ($PKG_VERSION) != tag ($TAG_VERSION)"; exit 1;
          fi

      - name: Build
        run: npm run build --if-present

      - name: Publish (scoped, public)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public